# Generated by Django 4.1.5 on 2023-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INVESTIGATOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('regid', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
    ]
