# Generated by Django 4.1.5 on 2023-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEDICINE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('store', models.CharField(max_length=255)),
                ('instock', models.BooleanField(default=False)),
            ],
        ),
    ]
