# Generated by Django 4.1.5 on 2023-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='incart',
            field=models.BooleanField(default=False),
        ),
    ]
